image: golang:latest

variables:
  TASK09_DIR: ./homework/09-unit-tests
  REPO_NAME: gitlab.ozon.dev/betkin/device-api

before_script:
  - export GO111MODULE=auto
  - make deps
  - make build
  - go install gotest.tools/gotestsum@latest
  - go mod tidy

stages:
  - test

golangci_lint:
  stage: test
  image: golangci/golangci-lint:v1.43
  script:
    - golangci-lint run ./...

unit_tests:
  stage: test
  script:
    - gotestsum --format testname --jsonfile json_report.txt $TASK09_DIR
  artifacts:
    paths:
      - json_report.txt